window.LR_DATA_SEED = [
  {
    "id": "2026_01_01",
    "Date": "2026",
    "Set": "001",
    "SetPadded": "01",
    "Number": "1",
    "NumberPadded": "01",
    "Time": 8,
    "Scene": "zoo",
    "Prompt": "You are learning to welcome visitors to the zoo. Listen to your manager and repeat what she says. ",
    "Audio": "S001-01.mp3",
    "Script": "We have a variety of wildlife.",
    "Type": "simple",
    "Length": 6,
    "Difficulty": 2,
    "Picture": "S001-01.png"
  },
  {
    "id": "2026_01_02",
    "Date": "2026",
    "Set": "001",
    "SetPadded": "01",
    "Number": "2",
    "NumberPadded": "02",
    "Time": 8,
    "Scene": "zoo",
    "Prompt": "You are learning to welcome visitors to the zoo. Listen to your manager and repeat what she says. ",
    "Audio": "S001-02.mp3",
    "Script": "Bears, wolves, and large cats are to the right.",
    "Type": "simple",
    "Length": 9,
    "Difficulty": 1,
    "Picture": "S001-02.png"
  },
  {
    "id": "2026_01_03",
    "Date": "2026",
    "Set": "001",
    "SetPadded": "01",
    "Number": "3",
    "NumberPadded": "03",
    "Time": 10,
    "Scene": "zoo",
    "Prompt": "You are learning to welcome visitors to the zoo. Listen to your manager and repeat what she says. ",
    "Audio": "S001-03.mp3",
    "Script": "You can find sea lions and elephants further down the path.",
    "Type": "simple",
    "Length": 11,
    "Difficulty": 2,
    "Picture": "S001-03.png"
  },
  {
    "id": "2026_01_04",
    "Date": "2026",
    "Set": "001",
    "SetPadded": "01",
    "Number": "4",
    "NumberPadded": "04",
    "Time": 10,
    "Scene": "zoo",
    "Prompt": "You are learning to welcome visitors to the zoo. Listen to your manager and repeat what she says. ",
    "Audio": "S001-04.mp3",
    "Script": "Please, no outside food or drinks, and do not feed the animals.",
    "Type": "imperative",
    "Length": 12,
    "Difficulty": 2,
    "Picture": "S001-04.png"
  },
  {
    "id": "2026_01_05",
    "Date": "2026",
    "Set": "001",
    "SetPadded": "01",
    "Number": "5",
    "NumberPadded": "05",
    "Time": 10,
    "Scene": "zoo",
    "Prompt": "You are learning to welcome visitors to the zoo. Listen to your manager and repeat what she says. ",
    "Audio": "S001-05.mp3",
    "Script": "Avoid banging or tapping on the displays and enclosures.",
    "Type": "imperative",
    "Length": 9,
    "Difficulty": 2,
    "Picture": "S001-05.png"
  },
  {
    "id": "2026_01_06",
    "Date": "2026",
    "Set": "001",
    "SetPadded": "01",
    "Number": "6",
    "NumberPadded": "06",
    "Time": 12,
    "Scene": "zoo",
    "Prompt": "You are learning to welcome visitors to the zoo. Listen to your manager and repeat what she says. ",
    "Audio": "S001-06.mp3",
    "Script": "For those with children, we offer summer camps and educational opportunities.",
    "Type": "non-finite clause",
    "Length": 11,
    "Difficulty": 3,
    "Picture": "S001-06.png"
  },
  {
    "id": "2026_01_07",
    "Date": "2026",
    "Set": "001",
    "SetPadded": "01",
    "Number": "7",
    "NumberPadded": "07",
    "Time": 12,
    "Scene": "zoo",
    "Prompt": "You are learning to welcome visitors to the zoo. Listen to your manager and repeat what she says. ",
    "Audio": "S001-07.mp3",
    "Script": "The visitor's center, located near the front entrance, can give you more information.",
    "Type": "non-finite clause",
    "Length": 13,
    "Difficulty": 3,
    "Picture": "S001-07.png"
  },
  {
    "id": "2026_02_01",
    "Date": "2026",
    "Set": "002",
    "SetPadded": "02",
    "Number": "1",
    "NumberPadded": "01",
    "Time": 8,
    "Scene": "campus gym",
    "Prompt": "You are learning how to guide new students through the campus gym. ",
    "Audio": "S002-01.mp3",
    "Script": "Welcome to our campus gym.",
    "Type": "simple",
    "Length": 5,
    "Difficulty": 1,
    "Picture": "S002-01.png"
  },
  {
    "id": "2026_02_02",
    "Date": "2026",
    "Set": "002",
    "SetPadded": "02",
    "Number": "2",
    "NumberPadded": "02",
    "Time": 8,
    "Scene": "campus gym",
    "Prompt": "You are learning how to guide new students through the campus gym. ",
    "Audio": "S002-02.mp3",
    "Script": "Cardio machines are near the entrance.",
    "Type": "simple",
    "Length": 6,
    "Difficulty": 1,
    "Picture": "S002-02.png"
  },
  {
    "id": "2026_02_03",
    "Date": "2026",
    "Set": "002",
    "SetPadded": "02",
    "Number": "3",
    "NumberPadded": "03",
    "Time": 10,
    "Scene": "campus gym",
    "Prompt": "You are learning how to guide new students through the campus gym. ",
    "Audio": "S002-03.mp3",
    "Script": "Free weights are in the back.",
    "Type": "simple",
    "Length": 6,
    "Difficulty": 1,
    "Picture": "S002-03.png"
  },
  {
    "id": "2026_02_04",
    "Date": "2026",
    "Set": "002",
    "SetPadded": "02",
    "Number": "4",
    "NumberPadded": "04",
    "Time": 10,
    "Scene": "campus gym",
    "Prompt": "You are learning how to guide new students through the campus gym. ",
    "Audio": "S002-04.mp3",
    "Script": "All of our locker rooms are equipped with showers and towels.",
    "Type": "non-finite clause",
    "Length": 11,
    "Difficulty": 3,
    "Picture": "S002-04.png"
  },
  {
    "id": "2026_02_05",
    "Date": "2026",
    "Set": "002",
    "SetPadded": "02",
    "Number": "5",
    "NumberPadded": "05",
    "Time": 10,
    "Scene": "campus gym",
    "Prompt": "You are learning how to guide new students through the campus gym. ",
    "Audio": "S002-05.mp3",
    "Script": "Our fitness instructors hold exercise classes over here.",
    "Type": "simple",
    "Length": 8,
    "Difficulty": 1,
    "Picture": "S002-05.png"
  },
  {
    "id": "2026_02_06",
    "Date": "2026",
    "Set": "002",
    "SetPadded": "02",
    "Number": "6",
    "NumberPadded": "06",
    "Time": 12,
    "Scene": "campus gym",
    "Prompt": "You are learning how to guide new students through the campus gym. ",
    "Audio": "S002-06.mp3",
    "Script": "You can check the schedule for available classes and timings.",
    "Type": "simple",
    "Length": 10,
    "Difficulty": 1,
    "Picture": "S002-06.png"
  },
  {
    "id": "2026_02_07",
    "Date": "2026",
    "Set": "002",
    "SetPadded": "02",
    "Number": "7",
    "NumberPadded": "07",
    "Time": 12,
    "Scene": "campus gym",
    "Prompt": "You are learning how to guide new students through the campus gym. ",
    "Audio": "S002-07.mp3",
    "Script": "If you have any questions, please seek assistance from the attendants at the help desk.",
    "Type": "adverbial clause",
    "Length": 15,
    "Difficulty": 4,
    "Picture": "S002-07.png"
  }
];
